[project]
name = "conv-freq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "pyyaml>=6.0.2",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]
